### ISSUE TITLE
Samsung Settings/Multi-control/etc not working - FIXED

### ISSUE THREAD

**Issue by Gah1101** [k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device#1]
Hi,

I tried various Samsung apps and updates, such as Second Screen and Samsung Notes, and they worked very well. However, I could not run Samsung Settings, where I wanted to use the Multi-Control tool. In your "read me" file, you mentioned that you were able to run it. How did you do that?

Thanks a lot for this batch.

**Comment by k0mraid3** [comment]
Good catch!! I did eventually get most things working except for Samsung Studio Plus, just updated the project, you will want to jump to the new step 2 and manually install the patched "Samsung System Support Service". Let me know if all goes well, Good luck!
