### ISSUE TITLE
Samsung Galaxy Book Exclusive Applications are not working and Samsung Settings app are not installed after reboot

### ISSUE THREAD

**Issue by Yograt** [k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device#2]
![image](https://github.com/k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device/assets/107334627/dd5b448d-69c0-43a7-b286-47999a82f47e)

I also did all the steps beside step 3 as it doesn't show at device manager anything else.

**Comment by k0mraid3** [comment]
Yup, I ran into this issue too, same with Samsung Studio Plus. Someone else also pointed out that Samsung Gallery also has an editor built in that is not working yet either. -- Either way, I'll upload a zip with the OEM apps to the repo. Look for the new zip in repo root.

Cred to Denis Nedry for pulling the apps off OEM firmware. This should handle this issue for those that have a problem getting the store to serve the apps.

**Comment by Yograt** [comment]
> Yup, I ran into this issue too, same with Samsung Studio Plus. Someone else also pointed out that Samsung Gallery also has an editor built in that is not working yet either. -- Either way, I'll upload a zip with the OEM apps to the repo. Look for the new zip in repo root.
> 
> Cred to Denis Nedry for pulling the apps off OEM firmware. This should handle this issue for those that have a problem getting the store to serve the apps. 

Alrighty! Thanks! I hope the new method of installing them works great!
