### ISSUE TITLE
My Samsung Phone doesn't show up on MultiControl

### ISSUE THREAD

**Issue by K4leds** [k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device#4]
I have an S233 ultra, in my laptop when I enable multi control for the first time it asks to update the "Samsung Continuity Service" app and it installs it from the Microsoft Store.
It gets enabled after that but my phone doesn't show up and it is enabled on both laptop and phone.

![SamsungSettingsApp_g8qJW5SeW2](https://github.com/k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device/assets/93814259/675b1c64-e233-435f-bc10-e6d4c6d644f3)

**Comment by vink2212** [comment]
Yeah same issue here. @k0mraid3 any idea what is going on ?

**Comment by k0mraid3** [comment]
Hmmmmm, This is Odd. Give me a few days to try and replicate this issue as well as a few others that recently popped up and see if I can identify the issue and create a fix. Thank you guys for bringing this up!

**Comment by k0mraid3** [comment]
ok,, have found this issue will be related to Issue #5 - This is due to driver updates. WWill continue work to sort this is main issue. Thx guys!
