### ISSUE TITLE
How to disable and remove the Spoofer BAT file

### ISSUE THREAD

**Issue by Ahoura-Bagherfar** [k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device#7]
Hello, I do not use this file anymore. How do I delete it? Because every time I turn on the PC, cmd opens automatically

**Comment by k0mraid3** [comment]
1- navigate to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp and find the file, delete it. 
2- Just for good measure, open task manager and go to "startup" apps, then find the bat file in the list and disable it there as well. 
3- Reboot, it should be gone!

Let me know if any issues!
